name: AppMap Analysis
branding:
  icon: alert-circle
  color: purple
description: |
  Analyze the changes between two code revisions.
inputs:
  base-revision:
    description: |
      The base revision to compare against. The default is the GITHUB_BASE_REF, which
      is the name of the base ref or target branch of the pull request in a workflow run.
  head-revision:
    description: |
      The head revision to compare against. The default is the GITHUB_HEAD_REF, which
      is the name of the head ref or target branch of the pull request in a workflow run.
  github-token:
    description: |
      The GitHub token to use with the GitHub API to pull AppMap archives from build artifacts.
      Most commonly, you'll use `secrets.GITHUB_TOKEN`, which is automatically provided by GitHub.
  fetch-history-days:
    description: |
      The number of days of history to fetch in order to find the most recent ancestor that has
      an AppMap archive. If an archive is not found, within this time window,
      the entire history will be fetched. To disable history fetching completely, set this value to 0.
    default: '30'
  archive-retention-days:
    description: |
      Number of days that the archive artifacts are retained for. Note that the AppMap archives created
      by analyze-action are always built from the AppMaps on a PR branch, and therefore they are 
      inherently more ephemeral than the base branch AppMaps created the archive-action. Therefore
      a fairly short retention period is recommended. If artifacts need to be re-generated for
      some reason, the workflow job can be re-run.
    default: '7'
  thread-count:
    description:
      Number of worker threads to use for processing the archive. Defaults to the number of CPUs /
      cores, as reported by Node.js. If the worker machine has a high number of CPUs/cores, the
      archive action may become I/O-bound rather than CPU-bound, and better performance might be
      obtained by setting this value to a lower number.
  annotation-exclusions:
    description: |
      Directories to ignore when generating annotations. Please enter the exclusions as a space-separated
      list (e.g. build tmp dist).
    default: node_modules vendor
  include-sections:
    description: |
      Sections to include in the report. Enter the sections as a space-separated list
      (e.g. test-failures api). The default is to generate all sections except for those which are
      in beta / early access.
  exclude-sections:
    description: |
      Sections to exclude from the report. Enter the sections as a space-separated list
      (e.g. test-failures api). The default is to generate all sections except for those which are
      in beta / early access.
  verbose:
    description: Enable verbose logging.
outputs:
  report-dir:
    description: Directory containing the report files.
runs:
  using: 'node16'
  main: 'dist/analyze/index.js'
