name: AppMap Analysis
description: Analyze the changes between two code revisions.
inputs:
  base-revision:
    description: |
      The base revision to compare against. The default is the GITHUB_BASE_REF, which
      according to GitHub is the name of the base ref or target branch of the pull request in a workflow run.
  head-revision:
    description: |
      The head revision to compare against. The default is the GITHUB_SHA, which
      according to GitHub is the commit that triggered the workflow run.
  github-token:
    description: |
      The GitHub token to use with the GitHub API to pull AppMap archives from build artifacts.
      Most commonly, you'll use `secrets.GITHUB_TOKEN`, which is automatically provided by GitHub.
  verbose:
    description: Enable verbose logging.
    default: 'false'
outputs:
  report-dir:
    description: Directory containing the report files.
runs:
  using: 'node16'
  main: 'dist/preflight/index.js'
