name: AppMap Analysis
description: |
  Analyze the changes between two code revisions. 
inputs:
  base-revision:
    description: |
      The base revision to compare against. The default is the GITHUB_BASE_REF, which
      according to GitHub is the name of the base ref or target branch of the pull request in a workflow run.
  head-revision:
    description: |
      The head revision to compare against. The default is the GITHUB_SHA, which
      according to GitHub is the commit that triggered the workflow run.
  github-token:
    description: |
      The GitHub token to use with the GitHub API to pull AppMap archives from build artifacts.
      Most commonly, you'll use `secrets.GITHUB_TOKEN`, which is automatically provided by GitHub.
  fetch-history-days:
    description: |
      The number of days of history to fetch in order to find the most recent ancestor that has
      an AppMap archive. The default is 30 days. If an archive is not found, within this time window,
      the entire history will be fetched. To disable history fetching completely, set this value to 0.
  thread-count:
    description:
      Number of worker threads to use for processing the archive. Defaults to the number of CPUs /
      cores, as reported by Node.js. If the worker machine has a high number of CPUs/cores, the
      archive action may become I/O-bound rather than CPU-bound, and better performance might be
      obtained by setting this value to a lower number.
  annotation-exclusions:
    description: |
      Directories to ignore when generating annotations. Please enter the exclusions as a space-separated
      list (e.g. build tmp dist).
    default: node_modules vendor
  verbose:
    description: Enable verbose logging.
outputs:
  report-dir:
    description: Directory containing the report files.
runs:
  using: 'node16'
  main: 'dist/analyze/index.js'
