name: AppMap Archive

on:
  pull_request:
  schedule:
    # Keep the artifact up to date, as it will expire after 90 days.
    - cron: 1 1 1 * *

env:
  APPMAP_TELEMETRY_DISABLED: 'true'

jobs:
  appmap_archive_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # This is needed to see the version history, because
          # checkout action doesn't fetch the base or head branches
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Install and configure AppMap
        uses: getappmap/install-appmap-action@v1-pre.5
        id: install-appmap
      - name: Update AppMap tools to v2
        run: |
          curl -L -o /tmp/appmap https://github.com/getappmap/appmap-js/releases/download/%40appland%2Fappmap-preflight-v1.0-pre.2/appmap-preflight-linux-x64
          chmod a+x /tmp/appmap
      - name: Install dependency libraries
        run: yarn install
      - name: Build
        run: yarn build
      - name: Make AppMaps
        run: yarn appmap || true
      - name: Preflight
        id: preflight-report
        uses: ./
        with:
          base-revision: ${{ github.event.pull_request.base.sha }}
          head-revision: ${{ github.event.pull_request.head.sha }}
          verbose: true
      - name: Test
        run: yarn test
      - name: Build GitHub action
        run: yarn package
      - name: Commit changes
        # If you forgot to package the distribution, you'll see a commit added to your PR
        uses: EndBug/add-and-commit@v7
        with:
          add: dist
          message: 'chore: Packaged distribution of the GitHub action'
