name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

env:
  APPMAP_TELEMETRY_DISABLED: 'true'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependency libraries
        run: yarn install

      - name: Install AppMap
        uses: getappmap/install-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-type: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Save AppMaps
        uses: actions/cache/save@v3
        if: always()
        with:
          path: tmp/appmap
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

      - name: Commit changes
        # If you forgot to package the distribution, you'll see a commit added to your PR
        uses: EndBug/add-and-commit@v7
        if: github.event_name == 'pull_request'
        with:
          add: dist
          message: 'chore: Packaged distribution of the GitHub action'

      - uses: rickstaa/action-create-tag@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tag: v1
          force_push_tag: true

  appmap-analysis:
    if: always()
    needs: [test]
    uses: ./.github/workflows/appmap-analysis.yml
