on: [push]

jobs:
  install_appmap_job:
    runs-on: ubuntu-latest
    name: Build, test and package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and configure AppMap
        uses: getappmap/install-appmap-action@v1-pre.2
        id: install-appmap
      - name: Install dependency libraries
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Build GitHub action
        run: yarn package
      - name: Make AppMaps
        # appmap-agent-js@13.6.0 doesn't propagate the jest exit code, so the main Test step cannot be the AppMap step.
        run: yarn appmap
      - name: Create and store AppMaps archive
        uses: ./
        id: appmap-archive
      - name: Commit changes
        # If you forgot to package the distribution, you'll see a commit added to your PR
        uses: EndBug/add-and-commit@v7
        with:
          add: dist
          message: 'chore: Packaged distribution of the GitHub action'
